# Generated by Django 6.0.5 on 2026-05-11 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('altura', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('ataque', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('velocidad', models.IntegerField(default=0)),
                ('generacion', models.IntegerField(choices=[(1, 'Gen I — 1996'), (2, 'Gen II — 1999'), (3, 'Gen III — 2002'), (4, 'Gen IV — 2006'), (5, 'Gen V — 2010'), (6, 'Gen VI — 2013'), (7, 'Gen VII — 2016'), (8, 'Gen VIII — 2019'), (9, 'Gen IX — 2022')], default=1)),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#888888', max_length=7)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='comunidad/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to=settings.AUTH_USER_MODEL)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='pokedex.pokemon')),
            ],
            options={
                'verbose_name': 'Imagen comunidad',
                'verbose_name_plural': 'Imágenes comunidad',
                'ordering': ['-subida_en'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='pokedex.pokemon')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tipo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_tipo1', to='pokedex.tipo'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tipo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_tipo2', to='pokedex.tipo'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='pokedex.pokemon')),
            ],
            options={
                'verbose_name': 'Favorito',
                'unique_together': {('entrenador', 'pokemon')},
            },
        ),
    ]
