# Generated by Django 6.0.5 on 2026-06-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagencomunidad',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ataque_especial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defensa_especial',
            field=models.IntegerField(default=0),
        ),
    ]
